#!/bin/bash

set -euo pipefail
IFS=$'\n'

if [[ ${1-} == "-f" ]]; then
	force="hf"
	shift
else
	force=""
fi

function escape {
	printf "%s" "$1" | LC_ALL=C sed 's/[]\\\\/.$&*{}|+?()[^]/\\&/g'
}

dest="${1-$HOME/.config}"

[[ -d $dest ]] || mkdir -vp "$dest"
ln -vs$force "$(realpath plugins)" "$dest"

src="$(escape "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")\\/"
dest="$(escape "$(realpath "$HOME")")\\/"

find dotfiles -mindepth 1 -type d -and -not -name ".*" | \
	sed -E "s/^dotfiles\\//$dest./" | \
	xargs mkdir -vp
find dotfiles -mindepth 1 -type f -and -not -name ".*" | \
	sed -E "s/^dotfiles\\/(.*)/$src&"$'\\\n'"$dest.\\1/" | \
	xargs -n 2 ln -vs$force
