#!/bin/bash

function makedir {
	if [[ ${1-} ]]; then
		[[ -d $1 ]] || mkdir -vp "$@"
	fi
}

function link {
	local i dest
	if [[ ${1-} ]]; then
		if [[ ${2-} ]]; then
			dest="${@:(-1)}"
			i=$[$#-2]
			[[ ${dest:(-1)} == '/' ]] && set - "${@:1:$i}" "$dest$(basename "$1")"
			makedir "$(dirname "$dest")"
		fi
		[[ -e $dest ]] || ln -vs "$@"
	fi
}

set -eu

cfg="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

link "$cfg/bash_profile" "$HOME/.bash_profile"
link "$cfg/bashrc" "$HOME/.bashrc"
link "$cfg/coffeelint.json" "$HOME/.coffeelint.json"
link "$cfg/eslintrc.json" "$HOME/.eslintrc.json"
link "$cfg/gitconfig" "$HOME/.config/git/config"
link "$cfg/gitignore" "$HOME/.config/git/ignore"
link "$cfg/vimrc" "$HOME/.vim/vimrc"
link "$cfg/gvimrc" "$HOME/.vim/gvimrc"
link "$cfg/profile" "$HOME/.profile"
link "$cfg/scss-lint.yml" "$HOME/.scss-lint.yml"
link "$cfg/tern-config.json" "$HOME/.tern-config"
link "$cfg/localenv" "$HOME/.localenv"

if [[ $os == 'darwin' ]]; then
	ln -vs "$cfg/local.env.plist" ~/Library/LaunchAgents
fi
